In [ ]:
######################################################################################
Copyright (c) 2023, 2024 , Prof. Radhamadhab Dalai, ITER , Siksha O Aanusandhan University, 
Odisha, India
Author's email address :  radhamadhabdalai@soa.ac.in
#####################################################################################
print ("Welocome to MLshop")

In [3]:
import pandas as pd

In [ ]:
Copyright (c) 2023, 2024 Radhamadhab Dalai, ITER , Siksha O Aanusandhan University, 
Odisha, India
Author's email address :  radhamadhabdalai@soa.ac.in

#Goal

In this module, we will introduce simple naive implementations of supervised 
machine learning Aapproaches. 

#routine method for converting categorical(qualititaive data) to numerical data
import pandas as pd
import numpy as np
import matplotlib
from sklearn.model_selection import train_test_split
## For Naive Bayes 

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (accuracy_score, confusion_matrix, consensus_score, ConfusionMatrixDisplay, f1_score, classification_report)

data = pd.read_csv('fruit_data.csv')
df = pd.DataFrame(data)
#print(df)
cat_columns = df.select_dtypes(['object']).columns
df[cat_columns] = df[cat_columns].apply(lambda x: pd.factorize(x)[0])

# print dataframe
#df  
X = df.to_numpy()
X1 = X[:, 3:7]   ## features  : X -> x1, x2,.....xn
Y1 = X[:,1]      # Output : Y
# Now split the data into Training and Testing dataset
# Routine method for splitting numpy data
# Now split the data into Training and Testing dataset
# Routine method for splitting numpy data
X_train, X_test ,Y_train, Y_test = train_test_split(X1,Y1,test_size=0.33 , random_state= 42)

print(X_train)
print(Y_train)

In [13]:
print(X) 

[[  1.     0.     0.   192.     8.4    7.3    0.55]
 [  1.     0.     0.   180.     8.     6.8    0.59]
 [  1.     0.     0.   176.     7.4    7.2    0.6 ]
 [  2.     1.     1.    86.     6.2    4.7    0.8 ]
 [  2.     1.     1.    84.     6.     4.6    0.79]
 [  2.     1.     1.    80.     5.8    4.3    0.77]
 [  2.     1.     1.    80.     5.9    4.3    0.81]
 [  2.     1.     1.    76.     5.8    4.     0.81]
 [  1.     0.     2.   178.     7.1    7.8    0.92]
 [  1.     0.     2.   172.     7.4    7.     0.89]
 [  1.     0.     2.   166.     6.9    7.3    0.93]
 [  1.     0.     2.   172.     7.1    7.6    0.92]
 [  1.     0.     2.   154.     7.     7.1    0.88]
 [  1.     0.     3.   164.     7.3    7.7    0.7 ]
 [  1.     0.     3.   152.     7.6    7.3    0.69]
 [  1.     0.     3.   156.     7.7    7.1    0.69]
 [  1.     0.     3.   156.     7.6    7.5    0.67]
 [  1.     0.     3.   168.     7.5    7.6    0.73]
 [  1.     0.     4.   162.     7.5    7.1    0.83]
 [  1.     0